version: '3.8'

services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nhiot_dashboard
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - HOST=0.0.0.0
      - PYTHONUNBUFFERED=1
    restart: always
